In [1]:
# https://www.tensorflow.org/tutorials/estimators/linear
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf
import tensorflow.feature_column as fc

import os
import sys

import matplotlib.pyplot as plt
from IPython.display import clear_output

/Users/yukofeb/Work/python/lifetimes/env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/yukofeb/Work/python/lifetimes/env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/yukofeb/Work/python/lifetimes/env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/yukofeb/Work/python/l

In [2]:
tf.enable_eager_execution()

In [3]:
! git clone --depth 1 https://github.com/tensorflow/models

Cloning into 'models'...
remote: Enumerating objects: 3234, done.
remote: Counting objects: 100% (3234/3234), done.
remote: Compressing objects: 100% (2739/2739), done.
remote: Total 3234 (delta 592), reused 2059 (delta 419), pack-reused 0
Receiving objects: 100% (3234/3234), 370.70 MiB | 8.32 MiB/s, done.
Resolving deltas: 100% (592/592), done.
Checking out files: 100% (3060/3060), done.


In [3]:
models_path = os.path.join(os.getcwd(), 'models')
print(models_path)
sys.path.append(models_path)

/Users/yukofeb/Work/python/lifetimes/src/models


In [4]:
from official.r1.wide_deep import census_dataset
from official.r1.wide_deep import census_main

census_dataset.download("/tmp/census_data/")

In [5]:
if "PYTHONPATH" in os.environ:
  os.environ['PYTHONPATH'] += os.pathsep +  models_path
else:
  os.environ['PYTHONPATH'] = models_path

In [6]:
!python -m official.r1.wide_deep.census_main --help

/Users/yukofeb/Work/python/lifetimes/env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/yukofeb/Work/python/lifetimes/env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/yukofeb/Work/python/lifetimes/env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/yukofeb/Work/python/l

In [7]:
!python -m official.r1.wide_deep.census_main --model_type=wide --train_epochs=2

/Users/yukofeb/Work/python/lifetimes/env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/yukofeb/Work/python/lifetimes/env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/yukofeb/Work/python/lifetimes/env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/yukofeb/Work/python/l


W0909 14:46:40.180067 4398962112 deprecation_wrapper.py:119] From /Users/yukofeb/Work/python/lifetimes/src/models/official/r1/wide_deep/census_dataset.py:167: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

INFO:tensorflow:Parsing /tmp/census_data/adult.data
I0909 14:46:40.180274 4398962112 census_dataset.py:167] Parsing /tmp/census_data/adult.data

W0909 14:46:40.180409 4398962112 deprecation_wrapper.py:119] From /Users/yukofeb/Work/python/lifetimes/src/models/official/r1/wide_deep/census_dataset.py:168: The name tf.decode_csv is deprecated. Please use tf.io.decode_csv instead.

INFO:tensorflow:Calling model_fn.
I0909 14:46:40.233268 4398962112 estimator.py:1145] Calling model_fn.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0909 14:46:40.605824 4398962112 deprecation.py:323] From /Users/yukofeb/Work/python/lifetimes/env/lib/python3.6/site-packages/tensorflow/python/ops/sparse_ops.py:1719: add_di

INFO:tensorflow:global_step/sec: 340.983
I0909 14:46:48.360514 4398962112 basic_session_run_hooks.py:692] global_step/sec: 340.983
INFO:tensorflow:average_loss = 0.2436276, loss = 9.745104 (0.293 sec)
I0909 14:46:48.361006 4398962112 basic_session_run_hooks.py:260] average_loss = 0.2436276, loss = 9.745104 (0.293 sec)
INFO:tensorflow:loss = 9.745104, step = 1101 (0.293 sec)
I0909 14:46:48.361168 4398962112 basic_session_run_hooks.py:260] loss = 9.745104, step = 1101 (0.293 sec)
INFO:tensorflow:global_step/sec: 309.137
I0909 14:46:48.683979 4398962112 basic_session_run_hooks.py:692] global_step/sec: 309.137
INFO:tensorflow:average_loss = 0.41160455, loss = 16.464182 (0.323 sec)
I0909 14:46:48.684434 4398962112 basic_session_run_hooks.py:260] average_loss = 0.41160455, loss = 16.464182 (0.323 sec)
INFO:tensorflow:loss = 16.464182, step = 1201 (0.323 sec)
I0909 14:46:48.684596 4398962112 basic_session_run_hooks.py:260] loss = 16.464182, step = 1201 (0.323 sec)
INFO:tensorflow:global_step/

In [8]:
!ls  /tmp/census_data/

adult.data adult.test


In [9]:
train_file = "/tmp/census_data/adult.data"
test_file = "/tmp/census_data/adult.test"

In [68]:
import pandas

train_df = pandas.read_csv(train_file, header = None, names = census_dataset._CSV_COLUMNS)
test_df = pandas.read_csv(test_file, header = None, names = census_dataset._CSV_COLUMNS)

display(train_df)
display(test_df)

age         workclass  fnlwgt   education  education_num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital_status         occupation   relationship   race  gender  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capital_gain  capital_loss  hours_per_week native_country  \
0              2174             0              40  United-States   
1                 0             0              13  United-States   
2                 0             0              40  United-States   
3                 0             0              40  United-States   
4                 0             0              40           Cuba   
...             ...           ...             ...            ...   
32556             0             0              38  United-States   
32557             0             0              40  United-States   
32558             0             0              40  United-States   
32559             0             0              20  United-States   
32560         15024             0              40  United-States   

      income_bracket  
0              <=50K  
1              <=50K  
2              <=50K  
3              <=50K  
4              <=50K  
...              ...  
32556          <=50K  
32557           >50K  
32558          <=50K  
32559          <=50K  
32560           >50K  

[32561 rows x 15 columns]

age     workclass  fnlwgt     education  education_num  \
0       25       Private  226802          11th              7   
1       38       Private   89814       HS-grad              9   
2       28     Local-gov  336951    Assoc-acdm             12   
3       44       Private  160323  Some-college             10   
4       18             ?  103497  Some-college             10   
...    ...           ...     ...           ...            ...   
16276   39       Private  215419     Bachelors             13   
16277   64             ?  321403       HS-grad              9   
16278   38       Private  374983     Bachelors             13   
16279   44       Private   83891     Bachelors             13   
16280   35  Self-emp-inc  182148     Bachelors             13   

           marital_status         occupation    relationship  \
0           Never-married  Machine-op-inspct       Own-child   
1      Married-civ-spouse    Farming-fishing         Husband   
2      Married-civ-spouse    Protective-serv         Husband   
3      Married-civ-spouse  Machine-op-inspct         Husband   
4           Never-married                  ?       Own-child   
...                   ...                ...             ...   
16276            Divorced     Prof-specialty   Not-in-family   
16277             Widowed                  ?  Other-relative   
16278  Married-civ-spouse     Prof-specialty         Husband   
16279            Divorced       Adm-clerical       Own-child   
16280  Married-civ-spouse    Exec-managerial         Husband   

                     race  gender  capital_gain  capital_loss  hours_per_week  \
0                   Black    Male             0             0              40   
1                   White    Male             0             0              50   
2                   White    Male             0             0              40   
3                   Black    Male          7688             0              40   
4                   White  Female             0             0              30   
...                   ...     ...           ...           ...             ...   
16276               White  Female             0             0              36   
16277               Black    Male             0             0              40   
16278               White    Male             0             0              50   
16279  Asian-Pac-Islander    Male          5455             0              40   
16280               White    Male             0             0              60   

      native_country income_bracket  
0      United-States          <=50K  
1      United-States          <=50K  
2      United-States           >50K  
3      United-States           >50K  
4      United-States          <=50K  
...              ...            ...  
16276  United-States          <=50K  
16277  United-States          <=50K  
16278  United-States          <=50K  
16279  United-States          <=50K  
16280  United-States           >50K  

[16281 rows x 15 columns]

In [11]:
# 入力関数
def easy_input_function(df, label_key, num_epochs, shuffle, batch_size):
  label = df[label_key]
  ds = tf.data.Dataset.from_tensor_slices((dict(df),label))

  if shuffle:
    ds = ds.shuffle(10000)

  ds = ds.batch(batch_size).repeat(num_epochs)

  return ds

In [12]:
# データをTensorに変換
ds = easy_input_function(train_df, label_key='income_bracket', num_epochs=5, shuffle=True, batch_size=10)

for feature_batch, label_batch in ds.take(1):
  print('Some feature keys:', list(feature_batch.keys())[:5])
  print()
  print('A batch of Ages  :', feature_batch['age'])
  print()
  print('A batch of Labels:', label_batch )

Some feature keys: ['age', 'workclass', 'fnlwgt', 'education', 'education_num']

A batch of Ages  : tf.Tensor([63 57 43 44 25 30 54 35 41 75], shape=(10,), dtype=int32)

A batch of Labels: tf.Tensor(
[b'<=50K' b'<=50K' b'<=50K' b'<=50K' b'<=50K' b'<=50K' b'>50K' b'<=50K'
 b'<=50K' b'<=50K'], shape=(10,), dtype=string)


In [15]:
import inspect
print(inspect.getsource(census_dataset.input_fn))

def input_fn(data_file, num_epochs, shuffle, batch_size):
  """Generate an input function for the Estimator."""
  assert tf.gfile.Exists(data_file), (
      '%s not found. Please make sure you have run census_dataset.py and '
      'set the --data_dir argument to the correct path.' % data_file)

  def parse_csv(value):
    tf.logging.info('Parsing {}'.format(data_file))
    columns = tf.decode_csv(value, record_defaults=_CSV_COLUMN_DEFAULTS)
    features = dict(zip(_CSV_COLUMNS, columns))
    labels = features.pop('income_bracket')
    classes = tf.equal(labels, '>50K')  # binary classification
    return features, classes

  # Extract lines from input files using the Dataset API.
  dataset = tf.data.TextLineDataset(data_file)

  if shuffle:
    dataset = dataset.shuffle(buffer_size=_NUM_EXAMPLES['train'])

  dataset = dataset.map(parse_csv, num_parallel_calls=5)

  # We call repeat after shuffling, rather than before, to prevent separate
  # epochs from blending together.
  dataset = 

In [73]:
# データをTensorに変換
ds = census_dataset.input_fn(train_file, num_epochs=5, shuffle=True, batch_size=10)

for feature_batch, label_batch in ds.take(1):
  print('Feature keys:', list(feature_batch.keys())[:5])
  print()
  print('Age batch   :', feature_batch['age'])
  print()
  print('Label batch :', label_batch )

INFO:tensorflow:Parsing /tmp/census_data/adult.data
Feature keys: ['age', 'workclass', 'fnlwgt', 'education', 'education_num']

Age batch   : tf.Tensor([53 31 46 40 54 44 46 25 38 53], shape=(10,), dtype=int32)

Label batch : tf.Tensor([False False False  True False  True False False False False], shape=(10,), dtype=bool)


In [17]:
import functools

train_inpf = functools.partial(census_dataset.input_fn, train_file, num_epochs=2, shuffle=True, batch_size=64)
test_inpf = functools.partial(census_dataset.input_fn, test_file, num_epochs=1, shuffle=False, batch_size=64)

In [18]:
train_inpf

functools.partial(<function input_fn at 0x12b66d6a8>, '/tmp/census_data/adult.data', num_epochs=2, shuffle=True, batch_size=64)

In [75]:
## 数値列 ##
# feature_column
age = fc.numeric_column('age')
age

NumericColumn(key='age', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)

In [76]:
# ??
fc.input_layer(feature_batch, [age]).numpy()

array([[53.],
       [31.],
       [46.],
       [40.],
       [54.],
       [44.],
       [46.],
       [25.],
       [38.],
       [53.]], dtype=float32)

In [78]:
# training,evaluate
classifier = tf.estimator.LinearClassifier(feature_columns=[age])
classifier.train(train_inpf)
result = classifier.evaluate(test_inpf)

clear_output()
print(result)

{'accuracy': 0.75198084, 'accuracy_baseline': 0.76377374, 'auc': 0.678357, 'auc_precision_recall': 0.3113919, 'average_loss': 0.5223577, 'label/mean': 0.23622628, 'loss': 33.351, 'precision': 0.15957446, 'prediction/mean': 0.23507322, 'recall': 0.011700468, 'global_step': 20351}


In [92]:
for key, value in result.items():
    print(key, value)

accuracy 0.75198084
accuracy_baseline 0.76377374
auc 0.678357
auc_precision_recall 0.3113919
average_loss 0.5223577
label/mean 0.23622628
loss 33.351
precision 0.15957446
prediction/mean 0.23507322
recall 0.011700468
global_step 20351


In [24]:
# feature_column
education_num = tf.feature_column.numeric_column('education_num')
capital_gain = tf.feature_column.numeric_column('capital_gain')
capital_loss = tf.feature_column.numeric_column('capital_loss')
hours_per_week = tf.feature_column.numeric_column('hours_per_week')

my_numeric_columns = [age,education_num, capital_gain, capital_loss, hours_per_week]

fc.input_layer(feature_batch, my_numeric_columns).numpy()

array([[  67., 6418.,    0.,    9.,   58.],
       [  38.,    0.,    0.,    9.,   42.],
       [  28., 4650.,    0.,   11.,   40.],
       [  31.,    0.,    0.,   11.,   40.],
       [  37.,    0.,    0.,   13.,   15.],
       [  34.,    0.,    0.,    9.,   40.],
       [  46.,    0.,    0.,   12.,   40.],
       [  38.,    0.,    0.,    7.,   50.],
       [  30.,    0.,    0.,   11.,   49.],
       [  18.,    0.,    0.,    7.,   16.]], dtype=float32)

In [25]:
classifier = tf.estimator.LinearClassifier(feature_columns=my_numeric_columns)
classifier.train(train_inpf)

result = classifier.evaluate(test_inpf)

clear_output()

for key,value in sorted(result.items()):
  print('%s: %s' % (key, value))

accuracy: 0.7859468
accuracy_baseline: 0.76377374
auc: 0.66974527
auc_precision_recall: 0.50426835
average_loss: 0.5937543
global_step: 1018
label/mean: 0.23622628
loss: 37.909466
precision: 0.6424625
prediction/mean: 0.22032878
recall: 0.21164846


In [27]:
for key, value in result.items():
    print('{}: {}'.format(key, value))

accuracy: 0.785946786403656
accuracy_baseline: 0.7637737393379211
auc: 0.6697452664375305
auc_precision_recall: 0.5042683482170105
average_loss: 0.5937542915344238
label/mean: 0.23622627556324005
loss: 37.90946578979492
precision: 0.6424624919891357
prediction/mean: 0.22032877802848816
recall: 0.21164846420288086
global_step: 1018


In [28]:
## カテゴリ列 ##
relationship = fc.categorical_column_with_vocabulary_list(
    'relationship',
    ['Husband', 'Not-in-family', 'Wife', 'Own-child', 'Unmarried', 'Other-relative'])

In [31]:
fc.input_layer(feature_batch, [age, fc.indicator_column(relationship)])

Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.


<tf.Tensor: id=5101, shape=(10, 7), dtype=float32, numpy=
array([[67.,  1.,  0.,  0.,  0.,  0.,  0.],
       [38.,  1.,  0.,  0.,  0.,  0.,  0.],
       [28.,  0.,  1.,  0.,  0.,  0.,  0.],
       [31.,  0.,  0.,  0.,  0.,  1.,  0.],
       [37.,  0.,  1.,  0.,  0.,  0.,  0.],
       [34.,  1.,  0.,  0.,  0.,  0.,  0.],
       [46.,  0.,  1.,  0.,  0.,  0.,  0.],
       [38.,  1.,  0.,  0.,  0.,  0.,  0.],
       [30.,  0.,  1.,  0.,  0.,  0.,  0.],
       [18.,  0.,  0.,  0.,  1.,  0.,  0.]], dtype=float32)>

In [32]:
# カテゴリがわからない場合は以下のようにする
occupation = tf.feature_column.categorical_column_with_hash_bucket(
    'occupation', hash_bucket_size=1000)

In [34]:
for item in feature_batch['occupation'].numpy():
    print(item.decode())

Transport-moving
Exec-managerial
Prof-specialty
Handlers-cleaners
Tech-support
Handlers-cleaners
Craft-repair
Sales
Craft-repair
Prof-specialty


In [37]:
occupation_result = fc.input_layer(feature_batch, [fc.indicator_column(occupation)])

occupation_result.numpy().shape

Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.


(10, 1000)

In [38]:
tf.argmax(occupation_result, axis=1).numpy()

array([420, 800, 979,  10, 413,  10, 466, 631, 466, 979])

In [39]:
education = tf.feature_column.categorical_column_with_vocabulary_list(
    'education', [
        'Bachelors', 'HS-grad', '11th', 'Masters', '9th', 'Some-college',
        'Assoc-acdm', 'Assoc-voc', '7th-8th', 'Doctorate', 'Prof-school',
        '5th-6th', '10th', '1st-4th', 'Preschool', '12th'])

marital_status = tf.feature_column.categorical_column_with_vocabulary_list(
    'marital_status', [
        'Married-civ-spouse', 'Divorced', 'Married-spouse-absent',
        'Never-married', 'Separated', 'Married-AF-spouse', 'Widowed'])

workclass = tf.feature_column.categorical_column_with_vocabulary_list(
    'workclass', [
        'Self-emp-not-inc', 'Private', 'State-gov', 'Federal-gov',
        'Local-gov', '?', 'Self-emp-inc', 'Without-pay', 'Never-worked'])


my_categorical_columns = [relationship, occupation, education, marital_status, workclass]

In [40]:
# training, evaluate
classifier = tf.estimator.LinearClassifier(feature_columns=my_numeric_columns+my_categorical_columns)
classifier.train(train_inpf)
result = classifier.evaluate(test_inpf)

clear_output()

for key,value in sorted(result.items()):
  print('%s: %s' % (key, value))

accuracy: 0.80799705
accuracy_baseline: 0.76377374
auc: 0.8296772
auc_precision_recall: 0.5842983
average_loss: 0.5848342
global_step: 1018
label/mean: 0.23622628
loss: 37.339943
precision: 0.61904764
prediction/mean: 0.21870618
recall: 0.48673946


In [43]:
## 派生特徴列 ##
# 特徴をカテゴリ化する
age_buckets = tf.feature_column.bucketized_column(
    age, boundaries=[18, 25, 30, 35, 40, 45, 50, 55, 60, 65])
age_buckets

BucketizedColumn(source_column=NumericColumn(key='age', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), boundaries=(18, 25, 30, 35, 40, 45, 50, 55, 60, 65))

In [44]:
fc.input_layer(feature_batch, [age, age_buckets]).numpy()

Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.


array([[67.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [38.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [28.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [31.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [37.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [34.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [46.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [38.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [30.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [18.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]],
      dtype=float32)

In [46]:
# 交差列
education_x_occupation = tf.feature_column.crossed_column(
    ['education', 'occupation'], hash_bucket_size=1000)
education_x_occupation

CrossedColumn(keys=('education', 'occupation'), hash_bucket_size=1000, hash_key=None)

In [47]:
age_buckets_x_education_x_occupation = tf.feature_column.crossed_column(
    [age_buckets, 'education', 'occupation'], hash_bucket_size=1000)
age_buckets_x_education_x_occupation

CrossedColumn(keys=(BucketizedColumn(source_column=NumericColumn(key='age', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None), boundaries=(18, 25, 30, 35, 40, 45, 50, 55, 60, 65)), 'education', 'occupation'), hash_bucket_size=1000, hash_key=None)

In [48]:
import tempfile

base_columns = [
    education, marital_status, relationship, workclass, occupation,
    age_buckets,
]

crossed_columns = [
    tf.feature_column.crossed_column(
        ['education', 'occupation'], hash_bucket_size=1000),
    tf.feature_column.crossed_column(
        [age_buckets, 'education', 'occupation'], hash_bucket_size=1000),
]

model = tf.estimator.LinearClassifier(
    model_dir=tempfile.mkdtemp(),
    feature_columns=base_columns + crossed_columns,
    optimizer=tf.train.FtrlOptimizer(learning_rate=0.1))

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/kc/sgj97qdx0bx4mvllm9d0svwh0000gn/T/tmpbfu91ubf', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x12d55d390>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [49]:
# train
train_inpf = functools.partial(census_dataset.input_fn, train_file,
                               num_epochs=40, shuffle=True, batch_size=64)

model.train(train_inpf)

clear_output()

In [50]:
# evaluate
results = model.evaluate(test_inpf)

clear_output()

for key,value in sorted(results.items()):
  print('%s: %0.2f' % (key, value))

accuracy: 0.84
accuracy_baseline: 0.76
auc: 0.88
auc_precision_recall: 0.69
average_loss: 0.35
global_step: 20351.00
label/mean: 0.24
loss: 22.64
precision: 0.69
prediction/mean: 0.24
recall: 0.55


In [64]:
classes[np.array(pred_class_id)]

array([['<=50K'],
       ['<=50K'],
       ['<=50K'],
       ['<=50K'],
       ['<=50K'],
       ['<=50K'],
       ['<=50K'],
       ['>50K'],
       ['<=50K'],
       ['<=50K'],
       ['<=50K'],
       ['>50K'],
       ['<=50K'],
       ['<=50K'],
       ['<=50K'],
       ['>50K'],
       ['<=50K'],
       ['<=50K'],
       ['<=50K'],
       ['>50K']], dtype='<U5')

In [51]:
# predict
import numpy as np

predict_df = test_df[:20].copy()

pred_iter = model.predict(
    lambda:easy_input_function(predict_df, label_key='income_bracket',
                               num_epochs=1, shuffle=False, batch_size=10))

classes = np.array(['<=50K', '>50K'])
pred_class_id = []

for pred_dict in pred_iter:
  pred_class_id.append(pred_dict['class_ids'])

predict_df['predicted_class'] = classes[np.array(pred_class_id)]
predict_df['correct'] = predict_df['predicted_class'] == predict_df['income_bracket']

clear_output()

predict_df[['income_bracket','predicted_class', 'correct']]

income_bracket predicted_class  correct
0           <=50K           <=50K     True
1           <=50K           <=50K     True
2            >50K           <=50K    False
3            >50K           <=50K    False
4           <=50K           <=50K     True
5           <=50K           <=50K     True
6           <=50K           <=50K     True
7            >50K            >50K     True
8           <=50K           <=50K     True
9           <=50K           <=50K     True
10           >50K           <=50K    False
11          <=50K            >50K    False
12          <=50K           <=50K     True
13          <=50K           <=50K     True
14           >50K           <=50K    False
15           >50K            >50K     True
16          <=50K           <=50K     True
17          <=50K           <=50K     True
18          <=50K           <=50K     True
19           >50K            >50K     True